services:
  app:
    image: ghcr.io/world-goes-to-hell/ysk-kanban:latest
    container_name: kanban-board
    ports:
      - "8080:8080"
    volumes:
      - /home/junu/docker_data/kanvanboard/data:/app/data
      - /home/junu/docker_data/kanvanboard/uploads:/app/uploads
    restart: unless-stopped
