spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/kanban}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:kanban}
    password: ${DB_PASSWORD:kanban}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 600000
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
